package com.example.padsou.ui.theme

const val FirstOnBoardingTitle = "Pas de sous ?"
const val FirstOnBoardingSubTitle = "Y'a padsou."
const val ItemOnBoardingCaption = "Accède aux 500 bons plans qu’on te propose chaque mois"
const val LastOnBoardingButton = "C'est parti !"

const val FirstRegisterTitle = "Bienvenue \uD83D\uDE0E"
const val FirstRegisterSubTitle = "Inscris-toi pour avoir les meilleurs plans étudiants !"
const val ItemRegisterPlaceholderMail = "Ton adresse e-mail"
const val ItemRegisterPlaceholderPassword = "Ton mot de passe"
const val ItemRegisterPlaceholderPasswordC = "Confirme ton mot de passe"
const val ItemRegisterCaption = "En t’inscrivant, tu acceptes les Conditions générales d’utilisation de Padsou"
const val ItemRegisterButton = "Se connecter"
const val LastRegisterFirstSentence = "Déjà un compte ? "
const val LastRegisterSecondSentence = "Connecte-toi !"

const val FirstLoginTitle = "Te revoilà ! \uD83D\uDD25"
const val FirstLoginSubTitle = "Reviens vite pour profiter des bons plans"
const val ItemLoginPlaceholderMail = "Ton adresse e-mail"
const val ItemLoginPlaceholderPassword = "Ton mot de passe"
const val ItemLoginPasswordForgot = "Mot de passe oublié ?"
const val ItemLoginButton = "Se connecter"
const val LastLoginFirstSentence = "Pas encore inscrit ? "
const val LastLoginSecondSentence = "Allez viens !"

const val FirstHomeTitle = "Coucou toi,"
const val FirstHomeSubTitle = "T’es en manque de thunes ?"
const val FirstHomeButton = "Cherche un bon plan"
const val LastHomeTitle = "Les plans du moment"
const val LastHomeSubTitle = "Voir tout"

const val FirstAddPlanTitle = "Ajouter"
const val FirstAddPlanSubTitle = "Un bon plan pour en faire profiter les autres"
const val LastAddPlanLabelTitle = "Titre"
const val LastAddPlanPlaceholderTitle = "Abonnement 1 an Basic-Fit"
const val LastAddPlanLabelDesc = "Description"
const val LastAddPlanPlaceholderDesc = "Ne soit pas trop bavard, on s’en fou, va à l’essentiel"
const val LastAddPlanLabelLien = "Lien"
const val LastAddPlanPlaceholderLien = "www.lienverstonbonplan.com"
const val LastAddPlanFirstButton = "Suivant"
const val LastAddPlanLabelPicture = "Photo du bon plan"
const val LastAddPlanSecondButton = "Ajouter ce bon plan"

const val ItemPlanLabelPropose = "Proposé par"
const val ItemPlanContentCom = "Chaque année, O’Tacos veut vous mettre bien. On sait que t’es étudiant et que c’est la galère, alors on t’a prévu des giga MAXI TACOS à des giga BAS PRIX. Ca se passe maintenant !"
const val LastPlanButton = "Profiter de l'offre"

const val FirstProfileTitle = "Mon Profil"
const val FirstProfileSubTitle = "Modifie tes infos affichées aux autres sur l’app"
const val LastProfileLabelPseudo = "Mon pseudo"
const val LastProfileLabelMail = "Adresse e-mail"
const val LastProfileLabelPassword = "Mot de passe"
const val LastProfileButton = "Enregistrer"